# selected fonts list
selected_fonts = [
    "stop",
    "Speed",
    "Shadow",
    "Rounded",
    "Roman",
    "Puffy",
    "Lean",
    "Larry 3D",
    "Jacky",
    "Ivrit",
    "Hollywood",
    "Fuzzy",
    "Dr Pepper",
    "Colossal",
    "Block",
    "Bell",
    "5 Line Oblique",
    "Electronic",
    "Bloody",
    "ANSI Shadow",
    "ANSI Regular",
    "33D-ASCII",
    "Train",
    "Sub-Zero",
    "Star Wars",
    "Standard",
    "Small Slant",
    "Slant",
    "Doom",
    "Big",
    "3D Diagonal",
]
